apiVersion: k8s.ovn.org/v1
kind: UserDefinedNetwork
metadata:
  finalizers:
    - k8s.ovn.org/user-defined-network-protection
  name: primary-udn
spec:
  topology: Layer2
  layer2:
    ipam:
      lifecycle: Persistent
    role: Primary
    subnets:
      - 10.1.1.0/24