[
  {
    "address": "00:00:00:00:00:00",
    "allmulti": 0,
    "broadcast": "00:00:00:00:00:00",
    "flags": [
      "LOOPBACK",
      "UP",
      "LOWER_UP"
    ],
    "gro_ipv4_max_size": 65536,
    "gro_max_size": 65536,
    "group": "default",
    "gso_ipv4_max_size": 65536,
    "gso_max_segs": 65535,
    "gso_max_size": 65536,
    "ifindex": 1,
    "ifname": "lo",
    "inet6_addr_gen_mode": "eui64",
    "link_type": "loopback",
    "linkmode": "DEFAULT",
    "max_mtu": 0,
    "min_mtu": 0,
    "mtu": 65536,
    "num_rx_queues": 1,
    "num_tx_queues": 1,
    "operstate": "UNKNOWN",
    "promiscuity": 0,
    "qdisc": "noqueue",
    "tso_max_segs": 65535,
    "tso_max_size": 524280,
    "txqlen": 1000
  },
  {
    "address": "0a:58:0a:83:00:54",
    "allmulti": 0,
    "broadcast": "ff:ff:ff:ff:ff:ff",
    "flags": [
      "BROADCAST",
      "MULTICAST",
      "UP",
      "LOWER_UP"
    ],
    "gro_ipv4_max_size": 65536,
    "gro_max_size": 65536,
    "group": "default",
    "gso_ipv4_max_size": 65536,
    "gso_max_segs": 65535,
    "gso_max_size": 65536,
    "ifindex": 2,
    "ifname": "eth0",
    "inet6_addr_gen_mode": "eui64",
    "link_index": 607,
    "link_netnsid": 0,
    "link_type": "ether",
    "linkinfo": {
      "info_kind": "veth"
    },
    "linkmode": "DEFAULT",
    "max_mtu": 65535,
    "min_mtu": 68,
    "mtu": 1400,
    "num_rx_queues": 128,
    "num_tx_queues": 128,
    "operstate": "UP",
    "promiscuity": 0,
    "qdisc": "noqueue",
    "tso_max_segs": 65535,
    "tso_max_size": 524280
  },
  {
    "address": "12:6f:ef:f4:36:9a",
    "allmulti": 1,
    "broadcast": "ff:ff:ff:ff:ff:ff",
    "flags": [
      "BROADCAST",
      "MULTICAST",
      "UP",
      "LOWER_UP"
    ],
    "gro_ipv4_max_size": 65536,
    "gro_max_size": 65536,
    "group": "default",
    "gso_ipv4_max_size": 65536,
    "gso_max_segs": 65535,
    "gso_max_size": 65536,
    "ifindex": 3,
    "ifname": "16711a0a730-nic",
    "inet6_addr_gen_mode": "eui64",
    "link_index": 608,
    "link_netnsid": 0,
    "link_type": "ether",
    "linkinfo": {
      "info_kind": "veth",
      "info_slave_data": {
        "bcast_flood": true,
        "bridge_id": "8000.12:6f:ef:f4:36:9a",
        "config_pending": 0,
        "cost": 2,
        "designated_cost": 0,
        "designated_port": 32769,
        "fastleave": false,
        "flood": true,
        "forward_delay_timer": 0.00,
        "group_fwd_mask": "0",
        "group_fwd_mask_str": "0x0",
        "guard": false,
        "hairpin": false,
        "hold_timer": 0.00,
        "id": "0x8001",
        "isolated": false,
        "learning": false,
        "locked": false,
        "mab": false,
        "mcast_flood": true,
        "mcast_to_unicast": false,
        "message_age_timer": 0.00,
        "multicast_router": 1,
        "neigh_suppress": false,
        "no": "0x1",
        "priority": 32,
        "proxy_arp": false,
        "proxy_arp_wifi": false,
        "root_block": false,
        "root_id": "8000.12:6f:ef:f4:36:9a",
        "state": "forwarding",
        "topology_change_ack": 0,
        "vlan_tunnel": false
      },
      "info_slave_kind": "bridge"
    },
    "linkmode": "DEFAULT",
    "master": "k6t-16711a0a730",
    "max_mtu": 65535,
    "min_mtu": 68,
    "mtu": 1400,
    "num_rx_queues": 128,
    "num_tx_queues": 128,
    "operstate": "UP",
    "promiscuity": 1,
    "qdisc": "noqueue",
    "tso_max_segs": 65535,
    "tso_max_size": 524280
  },
  {
    "address": "02:00:00:00:00:00",
    "allmulti": 0,
    "broadcast": "ff:ff:ff:ff:ff:ff",
    "flags": [
      "BROADCAST",
      "MULTICAST",
      "UP",
      "LOWER_UP"
    ],
    "gro_ipv4_max_size": 65536,
    "gro_max_size": 65536,
    "group": "default",
    "gso_ipv4_max_size": 65536,
    "gso_max_segs": 65535,
    "gso_max_size": 65536,
    "ifindex": 4,
    "ifname": "k6t-eth0",
    "inet6_addr_gen_mode": "eui64",
    "link_type": "ether",
    "linkinfo": {
      "info_data": {
        "ageing_time": 30000,
        "bridge_id": "8000.2:0:0:0:0:0",
        "forward_delay": 1500,
        "gc_timer": 74.56,
        "group_addr": "01:80:c2:00:00:00",
        "group_fwd_mask": "0",
        "hello_time": 200,
        "hello_timer": 0.00,
        "max_age": 2000,
        "mcast_hash_elasticity": 16,
        "mcast_hash_max": 4096,
        "mcast_igmp_version": 2,
        "mcast_last_member_cnt": 2,
        "mcast_last_member_intvl": 100,
        "mcast_membership_intvl": 26000,
        "mcast_mld_version": 1,
        "mcast_querier": 0,
        "mcast_querier_intvl": 25500,
        "mcast_query_intvl": 12500,
        "mcast_query_response_intvl": 1000,
        "mcast_query_use_ifaddr": 0,
        "mcast_router": 1,
        "mcast_snooping": 1,
        "mcast_startup_query_cnt": 2,
        "mcast_startup_query_intvl": 3125,
        "mcast_stats_enabled": 0,
        "mcast_vlan_snooping": 0,
        "nf_call_arptables": 0,
        "nf_call_ip6tables": 0,
        "nf_call_iptables": 0,
        "no_linklocal_learn": 0,
        "priority": 32768,
        "root_id": "8000.2:0:0:0:0:0",
        "root_path_cost": 0,
        "root_port": 0,
        "stp_state": 0,
        "tcn_timer": 0.00,
        "topology_change": 0,
        "topology_change_detected": 0,
        "topology_change_timer": 0.00,
        "vlan_default_pvid": 1,
        "vlan_filtering": 0,
        "vlan_protocol": "802.1Q",
        "vlan_stats_enabled": 0,
        "vlan_stats_per_port": 0
      },
      "info_kind": "bridge"
    },
    "linkmode": "DEFAULT",
    "max_mtu": 65535,
    "min_mtu": 68,
    "mtu": 1400,
    "num_rx_queues": 1,
    "num_tx_queues": 1,
    "operstate": "UP",
    "promiscuity": 0,
    "qdisc": "noqueue",
    "tso_max_segs": 65535,
    "tso_max_size": 65536,
    "txqlen": 1000
  },
  {
    "address": "8a:47:bc:d4:8b:d0",
    "allmulti": 1,
    "broadcast": "ff:ff:ff:ff:ff:ff",
    "flags": [
      "BROADCAST",
      "MULTICAST",
      "UP",
      "LOWER_UP"
    ],
    "gro_ipv4_max_size": 65536,
    "gro_max_size": 65536,
    "group": "default",
    "gso_ipv4_max_size": 65536,
    "gso_max_segs": 65535,
    "gso_max_size": 65536,
    "ifindex": 5,
    "ifname": "tap0",
    "inet6_addr_gen_mode": "eui64",
    "link_type": "ether",
    "linkinfo": {
      "info_data": {
        "group": "qemu",
        "multi_queue": false,
        "persist": true,
        "pi": false,
        "type": "tap",
        "user": "qemu",
        "vnet_hdr": true
      },
      "info_kind": "tun",
      "info_slave_data": {
        "bcast_flood": true,
        "bridge_id": "8000.2:0:0:0:0:0",
        "config_pending": 0,
        "cost": 100,
        "designated_cost": 0,
        "designated_port": 32769,
        "fastleave": false,
        "flood": true,
        "forward_delay_timer": 0.00,
        "group_fwd_mask": "0",
        "group_fwd_mask_str": "0x0",
        "guard": false,
        "hairpin": false,
        "hold_timer": 0.00,
        "id": "0x8001",
        "isolated": false,
        "learning": true,
        "locked": false,
        "mab": false,
        "mcast_flood": true,
        "mcast_to_unicast": false,
        "message_age_timer": 0.00,
        "multicast_router": 1,
        "neigh_suppress": false,
        "no": "0x1",
        "priority": 32,
        "proxy_arp": false,
        "proxy_arp_wifi": false,
        "root_block": false,
        "root_id": "8000.2:0:0:0:0:0",
        "state": "forwarding",
        "topology_change_ack": 0,
        "vlan_tunnel": false
      },
      "info_slave_kind": "bridge"
    },
    "linkmode": "DEFAULT",
    "master": "k6t-eth0",
    "max_mtu": 65521,
    "min_mtu": 68,
    "mtu": 1400,
    "num_rx_queues": 1,
    "num_tx_queues": 1,
    "operstate": "UP",
    "promiscuity": 1,
    "qdisc": "fq_codel",
    "tso_max_segs": 65535,
    "tso_max_size": 65536,
    "txqlen": 1000
  },
  {
    "address": "12:6f:ef:f4:36:9a",
    "allmulti": 0,
    "broadcast": "ff:ff:ff:ff:ff:ff",
    "flags": [
      "BROADCAST",
      "MULTICAST",
      "UP",
      "LOWER_UP"
    ],
    "gro_ipv4_max_size": 65536,
    "gro_max_size": 65536,
    "group": "default",
    "gso_ipv4_max_size": 65536,
    "gso_max_segs": 65535,
    "gso_max_size": 65536,
    "ifindex": 6,
    "ifname": "k6t-16711a0a730",
    "inet6_addr_gen_mode": "eui64",
    "link_type": "ether",
    "linkinfo": {
      "info_data": {
        "ageing_time": 30000,
        "bridge_id": "8000.12:6f:ef:f4:36:9a",
        "forward_delay": 1500,
        "gc_timer": 198.47,
        "group_addr": "01:80:c2:00:00:00",
        "group_fwd_mask": "0",
        "hello_time": 200,
        "hello_timer": 0.00,
        "max_age": 2000,
        "mcast_hash_elasticity": 16,
        "mcast_hash_max": 4096,
        "mcast_igmp_version": 2,
        "mcast_last_member_cnt": 2,
        "mcast_last_member_intvl": 100,
        "mcast_membership_intvl": 26000,
        "mcast_mld_version": 1,
        "mcast_querier": 0,
        "mcast_querier_intvl": 25500,
        "mcast_query_intvl": 12500,
        "mcast_query_response_intvl": 1000,
        "mcast_query_use_ifaddr": 0,
        "mcast_router": 1,
        "mcast_snooping": 1,
        "mcast_startup_query_cnt": 2,
        "mcast_startup_query_intvl": 3125,
        "mcast_stats_enabled": 0,
        "mcast_vlan_snooping": 0,
        "nf_call_arptables": 0,
        "nf_call_ip6tables": 0,
        "nf_call_iptables": 0,
        "no_linklocal_learn": 0,
        "priority": 32768,
        "root_id": "8000.12:6f:ef:f4:36:9a",
        "root_path_cost": 0,
        "root_port": 0,
        "stp_state": 0,
        "tcn_timer": 0.00,
        "topology_change": 0,
        "topology_change_detected": 0,
        "topology_change_timer": 0.00,
        "vlan_default_pvid": 1,
        "vlan_filtering": 0,
        "vlan_protocol": "802.1Q",
        "vlan_stats_enabled": 0,
        "vlan_stats_per_port": 0
      },
      "info_kind": "bridge"
    },
    "linkmode": "DEFAULT",
    "max_mtu": 65535,
    "min_mtu": 68,
    "mtu": 1400,
    "num_rx_queues": 1,
    "num_tx_queues": 1,
    "operstate": "UP",
    "promiscuity": 0,
    "qdisc": "noqueue",
    "tso_max_segs": 65535,
    "tso_max_size": 65536,
    "txqlen": 1000
  },
  {
    "address": "7a:f1:ab:eb:e9:e1",
    "allmulti": 1,
    "broadcast": "ff:ff:ff:ff:ff:ff",
    "flags": [
      "BROADCAST",
      "MULTICAST",
      "UP",
      "LOWER_UP"
    ],
    "gro_ipv4_max_size": 65536,
    "gro_max_size": 65536,
    "group": "default",
    "gso_ipv4_max_size": 65536,
    "gso_max_segs": 65535,
    "gso_max_size": 65536,
    "ifindex": 7,
    "ifname": "tap16711a0a730",
    "inet6_addr_gen_mode": "eui64",
    "link_type": "ether",
    "linkinfo": {
      "info_data": {
        "group": "qemu",
        "multi_queue": false,
        "persist": true,
        "pi": false,
        "type": "tap",
        "user": "qemu",
        "vnet_hdr": true
      },
      "info_kind": "tun",
      "info_slave_data": {
        "bcast_flood": true,
        "bridge_id": "8000.12:6f:ef:f4:36:9a",
        "config_pending": 0,
        "cost": 100,
        "designated_cost": 0,
        "designated_port": 32770,
        "fastleave": false,
        "flood": true,
        "forward_delay_timer": 0.00,
        "group_fwd_mask": "0",
        "group_fwd_mask_str": "0x0",
        "guard": false,
        "hairpin": false,
        "hold_timer": 0.00,
        "id": "0x8002",
        "isolated": false,
        "learning": true,
        "locked": false,
        "mab": false,
        "mcast_flood": true,
        "mcast_to_unicast": false,
        "message_age_timer": 0.00,
        "multicast_router": 1,
        "neigh_suppress": false,
        "no": "0x2",
        "priority": 32,
        "proxy_arp": false,
        "proxy_arp_wifi": false,
        "root_block": false,
        "root_id": "8000.12:6f:ef:f4:36:9a",
        "state": "forwarding",
        "topology_change_ack": 0,
        "vlan_tunnel": false
      },
      "info_slave_kind": "bridge"
    },
    "linkmode": "DEFAULT",
    "master": "k6t-16711a0a730",
    "max_mtu": 65521,
    "min_mtu": 68,
    "mtu": 1400,
    "num_rx_queues": 1,
    "num_tx_queues": 1,
    "operstate": "UP",
    "promiscuity": 1,
    "qdisc": "fq_codel",
    "tso_max_segs": 65535,
    "tso_max_size": 65536,
    "txqlen": 1000
  },
  {
    "address": "02:86:5e:00:00:16",
    "allmulti": 0,
    "broadcast": "ff:ff:ff:ff:ff:ff",
    "flags": [
      "BROADCAST",
      "NOARP"
    ],
    "gro_ipv4_max_size": 65536,
    "gro_max_size": 65536,
    "group": "default",
    "gso_ipv4_max_size": 65536,
    "gso_max_segs": 65535,
    "gso_max_size": 65536,
    "ifindex": 8,
    "ifname": "pod16711a0a730",
    "inet6_addr_gen_mode": "eui64",
    "link_type": "ether",
    "linkinfo": {
      "info_kind": "dummy"
    },
    "linkmode": "DEFAULT",
    "max_mtu": 0,
    "min_mtu": 0,
    "mtu": 1400,
    "num_rx_queues": 1,
    "num_tx_queues": 1,
    "operstate": "DOWN",
    "promiscuity": 0,
    "qdisc": "noop",
    "tso_max_segs": 65535,
    "tso_max_size": 65536,
    "txqlen": 1000
  }
]
