---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-vm-localnet-cudn
  labels:
    # this must exist at namespace creation time
    # k8s.ovn.org/primary-user-defined-network: ""
    # this can be added later?
    # allow-cudn-1924: "true"
