---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-vm-pod

resources:
  - namespace.yaml

components:
  - ../components/vm

patches:
  - target:
      group: kubevirt.io
      kind: VirtualMachine
      name: .*
      version: v1
    patch: |-
      # rename VM
      - op: replace
        path: /metadata/name
        value: vm-pod