---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    description: Demo localnet secondary network on VLAN 1924
  name: demo-vlan-1924
spec:
  config: |-
    {
      "cniVersion": "0.4.0", 
      "name": "demo-vlan-1924",
      "type": "ovn-k8s-cni-overlay", 
      "topology": "localnet", 
      "netAttachDefName": "demo-vm-localnet/demo-vlan-1924",
      "vlanID": 1924,
      "ipam": {}
    }
